"use client";

import { useEffect, useMemo, useState } from "react";
import InteractiveClearanceChart from "@/components/playback/InteractiveClearanceChart";
import { loadMeasurementHistory, type MeasurementHistory, type MeasurementRtkEndpoint } from "@/components/playback/measurementHistoryApi";
import TaskBrowser from "@/components/workflow/TaskBrowser";
import { deleteSelectedTasks } from "@/components/workflow/taskApi";
import type { CollectionTask, WorkflowPageId } from "@/components/workflow/taskModel";

type Props={tasks:CollectionTask[];selectedTaskId:string|null;onSelectTask:(id:string)=>void;onDataChanged:()=>Promise<void>;onNavigate:(page:WorkflowPageId)=>void};
type HistoryState="idle"|"loading"|"empty"|"ready"|"error";
const fh=(v:number|null)=>v===null?"-- m":`${v.toFixed(3)} m`; const fd=(v:number|null)=>{if(v===null)return"--:--.---";const ms=Math.max(0,Math.round(v));return`${String(Math.floor(ms/60000)).padStart(2,"0")}:${String(Math.floor((ms%60000)/1000)).padStart(2,"0")}.${String(ms%1000).padStart(3,"0")}`}; const frate=(v:number|null)=>v===null?"-- Hz":`${v.toFixed(2)} Hz`; const frtk=(e:MeasurementRtkEndpoint|null)=>!e||!e.valid?"--":`${e.latitudeDeg.toFixed(7)}, ${e.longitudeDeg.toFixed(7)}`;
const canDeleteTask=(task:CollectionTask)=>task.status!=="采集中"&&task.status!=="已暂停";

export default function PlaybackWorkspace({tasks,selectedTaskId,onSelectTask,onDataChanged,onNavigate}:Props){
  const selectedTask=tasks.find(t=>t.taskId===selectedTaskId)??null; const [historyState,setHistoryState]=useState<HistoryState>("idle"); const [history,setHistory]=useState<MeasurementHistory|null>(null); const [historyError,setHistoryError]=useState<string|null>(null);
  const [checked,setChecked]=useState<Set<string>>(new Set()); const [deleting,setDeleting]=useState(false); const [deleteMessage,setDeleteMessage]=useState<string|null>(null); const [deleteError,setDeleteError]=useState(false);
  const disabledTaskIds=useMemo(()=>new Set(tasks.filter(task=>!canDeleteTask(task)).map(task=>task.taskId)),[tasks]);
  useEffect(()=>{let cancelled=false;setHistory(null);setHistoryError(null);if(!selectedTask){setHistoryState("idle");return()=>{cancelled=true};}if(!selectedTask.hasMeasurements){setHistoryState("empty");return()=>{cancelled=true};}setHistoryState("loading");loadMeasurementHistory(selectedTask.taskId).then(h=>{if(!cancelled){setHistory(h);setHistoryState(h.samples.length>1?"ready":"empty")}}).catch(e=>{if(!cancelled){setHistoryState("error");setHistoryError(e instanceof Error?e.message:"历史记录读取失败")}});return()=>{cancelled=true};},[selectedTask]);
  useEffect(()=>{setChecked(c=>new Set([...c].filter(id=>tasks.some(t=>t.taskId===id)&&!disabledTaskIds.has(id))));},[tasks,disabledTaskIds]);
  const stats=history?.statistics??null; const validRate=stats&&stats.totalSamples>0?`${((stats.validSamples/stats.totalSamples)*100).toFixed(1)}%`:"--"; const taskEnded=selectedTask?.status==="已停止"||selectedTask?.status==="异常中断"||selectedTask?.status==="失败";
  const measurementRows=useMemo(()=>[["最低净空高度",fh(stats?.minimumHeightM??null)],["平均净空高度",fh(stats?.averageHeightM??null)],["最高净空高度",fh(stats?.maximumHeightM??null)],["有效采样数量",stats?`${stats.validSamples} / ${stats.totalSamples}`:"--"],["记录时长",fd(stats?.durationMs??null)],["实际平均频率",frate(stats?.actualAverageSampleRateHz??null)]],[stats]);
  const qualityRows=useMemo(()=>[["数据来源",history?.dataOrigin==="test_fixture"?"界面测试数据":history?"设备记录":"--"],["标称采样频率",stats?`${stats.nominalSampleRateHz.toFixed(0)} Hz`:"--"],["有效采样比例",validRate],["无效采样数量",stats?String(stats.invalidSamples):"--"],["暂停区间",history?`${history.pauseIntervalCount} 段`:"--"],["记录完整性",history?history.complete?"完整":"异常中断或未完整结束":"--"]],[history,stats,validRate]);
  const toggle=(id:string)=>{if(disabledTaskIds.has(id))return;setChecked(c=>{const n=new Set(c);n.has(id)?n.delete(id):n.add(id);return n;});};
  const toggleGroup=(_:string,ids:string[])=>setChecked(c=>{const n=new Set(c);const eligible=ids.filter(id=>!disabledTaskIds.has(id));const all=eligible.length>0&&eligible.every(id=>n.has(id));eligible.forEach(id=>all?n.delete(id):n.add(id));return n;});
  const toggleAll=(ids:string[])=>toggleGroup("all",ids);
  const deleteIds=[...checked];
  const deleteSelected=async()=>{if(deleteIds.length===0||deleting)return;const confirmed=window.confirm(`确定删除所选 ${deleteIds.length} 个任务吗？`);if(!confirmed)return;setDeleting(true);setDeleteMessage(null);setDeleteError(false);try{const result=await deleteSelectedTasks(deleteIds);setChecked(new Set());setDeleteMessage(`已删除 ${result.deletedTaskCount} 个任务`);await onDataChanged();}catch(e){setDeleteError(true);setDeleteMessage(e instanceof Error?e.message:"任务删除失败");}finally{setDeleting(false)}};
  const recordState=historyState==="loading"?"读取中":historyState==="ready"?`${stats?.validSamples??0} 条有效记录`:historyState==="error"?"读取失败":selectedTask?.localDataPurgedAt?"本地数据已清理":selectedTask?.hasMeasurements?"记录为空":selectedTask?"无记录":"--";
  return <div className="page-stack playback-page playback-page--clearance">
    <section className="panel workflow-context-bar"><div className="workflow-context-bar__identity"><span>当前任务</span><strong>{selectedTask?.displayId??"尚未选择任务"}</strong><small>{selectedTask?`${selectedTask.tunnelCode} · ${selectedTask.tunnelName} · ${selectedTask.status}`:"任务按创建日期分组，可选择单个、多个或当前筛选结果后删除"}</small></div><div className="workflow-context-bar__states"><div><span>任务状态</span><strong>{selectedTask?.status??"--"}</strong></div><div><span>高度记录</span><strong>{recordState}</strong></div><div><span>已选删除</span><strong>{checked.size} 项</strong></div><div><span>本地数据</span><strong>{selectedTask?.localDataPurgedAt?"已清理":selectedTask?.hasMeasurements?"存在":"无"}</strong></div></div><div className="workflow-context-bar__actions"><button type="button" className="button" onClick={()=>onNavigate("dashboard")}>返回采集首页</button><button type="button" className="button button--primary" disabled={!selectedTask} onClick={()=>onNavigate("report")}>进入报告导出</button><button type="button" className="button button--danger-outline" disabled={deleteIds.length===0||deleting} onClick={()=>void deleteSelected()}>{deleting?"正在删除":`删除所选任务${deleteIds.length?` (${deleteIds.length})`:""}`}</button></div></section>
    {deleteMessage&&<p className={`batch-operation-message${deleteError?" is-error":""}`}>{deleteMessage}</p>}
    <section className="playback-layout playback-layout--clearance"><TaskBrowser tasks={tasks} selectedTaskId={selectedTaskId} onSelectTask={onSelectTask} heading="选择回放任务" sortOrder="asc" selectable showSelectAll checkedTaskIds={checked} disabledTaskIds={disabledTaskIds} onToggleChecked={toggle} onToggleDateChecked={toggleGroup} onToggleAllChecked={toggleAll}/><main className="playback-clearance-main"><article className="panel playback-clearance-panel"><header className="playback-clearance-panel__head"><div><span>50 Hz 测量序列</span><h2>{selectedTask?`${selectedTask.displayId} 完整净空高度曲线`:"完整净空高度曲线"}</h2><p>支持拖拽平移、滚轮缩放和双击复位，无效采样保持断开。</p></div><span className={`workflow-status ${history?.dataOrigin==="test_fixture"?"workflow-status--warn":taskEnded?"workflow-status--ok":"workflow-status--idle"}`}>{history?.dataOrigin==="test_fixture"?"界面测试数据":taskEnded?"任务已结束":selectedTask?"任务未结束":"待选择"}</span></header><InteractiveClearanceChart key={selectedTask?.taskId??"no-task"} samples={history?.samples??[]} emptyTitle={historyState==="loading"?"正在读取任务高度记录":historyState==="error"?"任务高度记录读取失败":selectedTask?.localDataPurgedAt?"本地测量数据已清理":selectedTask?"当前任务没有可显示的高度记录":"请选择任务查看完整净空高度曲线"} emptyDescription={historyState==="error"?historyError??"请检查后端日志。":selectedTask?.localDataPurgedAt?"本地测量数据已清理，无法回放。":"页面不会使用模拟曲线替代缺失记录。"}/></article></main><aside className="panel playback-inspector playback-inspector--clearance"><header><div><span>任务记录</span><strong>统计与数据质量</strong></div></header><section className="inspector-section"><h3>隧道信息</h3><dl><div><dt>任务编号</dt><dd>{selectedTask?.displayId??"--"}</dd></div><div><dt>隧道编号</dt><dd>{selectedTask?.tunnelCode??"--"}</dd></div><div><dt>隧道名称</dt><dd>{selectedTask?.tunnelName??"--"}</dd></div><div><dt>检测车道</dt><dd>{history?.lane??selectedTask?.lane??"未记录"}</dd></div></dl></section><section className="inspector-section"><h3>测量统计</h3><dl>{measurementRows.map(([l,v])=><div key={l}><dt>{l}</dt><dd>{v}</dd></div>)}</dl></section><section className="inspector-section"><h3>隧道端点</h3><dl><div><dt>入口 RTK</dt><dd>{frtk(history?.entryRtk??null)}</dd></div><div><dt>出口 RTK</dt><dd>{frtk(history?.exitRtk??null)}</dd></div></dl></section><section className="inspector-section"><h3>数据质量</h3><dl>{qualityRows.map(([l,v])=><div key={l}><dt>{l}</dt><dd>{v}</dd></div>)}</dl></section></aside></section>
  </div>;
}
