"use client";

import { useEffect, useMemo, useState } from "react";
import InteractiveClearanceChart from "@/components/playback/InteractiveClearanceChart";
import { loadMeasurementHistory, type MeasurementHistory, type MeasurementRtkEndpoint } from "@/components/playback/measurementHistoryApi";
import TaskBrowser from "@/components/workflow/TaskBrowser";
import { purgeTaskData } from "@/components/workflow/taskApi";
import type { CollectionTask, WorkflowPageId } from "@/components/workflow/taskModel";

type Props={tasks:CollectionTask[];selectedTaskId:string|null;onSelectTask:(id:string)=>void;onDeleteTask:(id:string)=>Promise<void>;onDataChanged:()=>Promise<void>;onNavigate:(page:WorkflowPageId)=>void};
type HistoryState="idle"|"loading"|"empty"|"ready"|"error";
const fh=(v:number|null)=>v===null?"-- m":`${v.toFixed(3)} m`; const fd=(v:number|null)=>{if(v===null)return"--:--.---";const ms=Math.max(0,Math.round(v));return`${String(Math.floor(ms/60000)).padStart(2,"0")}:${String(Math.floor((ms%60000)/1000)).padStart(2,"0")}.${String(ms%1000).padStart(3,"0")}`}; const frate=(v:number|null)=>v===null?"-- Hz":`${v.toFixed(2)} Hz`; const frtk=(e:MeasurementRtkEndpoint|null)=>!e||!e.valid?"--":`${e.latitudeDeg.toFixed(7)}, ${e.longitudeDeg.toFixed(7)}`; const bytes=(v:number)=>v>=1024**3?`${(v/1024**3).toFixed(2)} GiB`:v>=1024**2?`${(v/1024**2).toFixed(1)} MiB`:v>=1024?`${(v/1024).toFixed(1)} KiB`:`${v} B`;

function DeleteDialog({task,deleting,error,onCancel,onConfirm}:{task:CollectionTask;deleting:boolean;error:string|null;onCancel:()=>void;onConfirm:()=>void}){return <div className="task-dialog-mask" role="dialog" aria-modal="true"><section className="task-dialog-panel delete-task-dialog"><header className="task-dialog-head"><div><h2>删除任务 {task.displayId}</h2><p>任务将从列表移除。此操作不负责释放测量文件空间。</p></div><button type="button" disabled={deleting} onClick={onCancel}>×</button></header><dl className="delete-task-dialog__summary"><div><dt>隧道编号</dt><dd>{task.tunnelCode}</dd></div><div><dt>隧道名称</dt><dd>{task.tunnelName}</dd></div><div><dt>任务状态</dt><dd>{task.status}</dd></div><div><dt>本地数据</dt><dd>{task.localDataPurgedAt?"已清理":task.hasMeasurements?"存在":"无"}</dd></div></dl>{error&&<p className="task-dialog-error">{error}</p>}<footer className="task-dialog-actions"><button type="button" className="button" disabled={deleting} onClick={onCancel}>取消</button><button type="button" className="button button--danger" disabled={deleting} onClick={onConfirm}>{deleting?"正在删除":"确认删除"}</button></footer></section></div>}

export default function PlaybackWorkspace({tasks,selectedTaskId,onSelectTask,onDeleteTask,onDataChanged,onNavigate}:Props){
  const selectedTask=tasks.find(t=>t.taskId===selectedTaskId)??null; const [historyState,setHistoryState]=useState<HistoryState>("idle"); const [history,setHistory]=useState<MeasurementHistory|null>(null); const [historyError,setHistoryError]=useState<string|null>(null);
  const [checked,setChecked]=useState<Set<string>>(new Set()); const [purging,setPurging]=useState(false); const [purgeMessage,setPurgeMessage]=useState<string|null>(null); const [purgeError,setPurgeError]=useState(false);
  const [deleteOpen,setDeleteOpen]=useState(false); const [deleting,setDeleting]=useState(false); const [deleteError,setDeleteError]=useState<string|null>(null);
  useEffect(()=>{let cancelled=false;setHistory(null);setHistoryError(null);if(!selectedTask){setHistoryState("idle");return()=>{cancelled=true};}if(!selectedTask.hasMeasurements){setHistoryState("empty");return()=>{cancelled=true};}setHistoryState("loading");loadMeasurementHistory(selectedTask.taskId).then(h=>{if(!cancelled){setHistory(h);setHistoryState(h.samples.length>1?"ready":"empty")}}).catch(e=>{if(!cancelled){setHistoryState("error");setHistoryError(e instanceof Error?e.message:"历史记录读取失败")}});return()=>{cancelled=true};},[selectedTask]);
  useEffect(()=>{setChecked(c=>new Set([...c].filter(id=>tasks.some(t=>t.taskId===id))));},[tasks]);
  const stats=history?.statistics??null; const validRate=stats&&stats.totalSamples>0?`${((stats.validSamples/stats.totalSamples)*100).toFixed(1)}%`:"--"; const taskEnded=selectedTask?.status==="已停止"||selectedTask?.status==="异常中断"||selectedTask?.status==="失败"; const deleteBlocked=selectedTask?.status==="采集中"||selectedTask?.status==="已暂停";
  const measurementRows=useMemo(()=>[["最低净空高度",fh(stats?.minimumHeightM??null)],["平均净空高度",fh(stats?.averageHeightM??null)],["最高净空高度",fh(stats?.maximumHeightM??null)],["有效采样数量",stats?`${stats.validSamples} / ${stats.totalSamples}`:"--"],["记录时长",fd(stats?.durationMs??null)],["实际平均频率",frate(stats?.actualAverageSampleRateHz??null)]],[stats]);
  const qualityRows=useMemo(()=>[["数据来源",history?.dataOrigin==="test_fixture"?"界面测试数据":history?"设备记录":"--"],["标称采样频率",stats?`${stats.nominalSampleRateHz.toFixed(0)} Hz`:"--"],["有效采样比例",validRate],["无效采样数量",stats?String(stats.invalidSamples):"--"],["暂停区间",history?`${history.pauseIntervalCount} 段`:"--"],["记录完整性",history?history.complete?"完整":"异常中断或未完整结束":"--"]],[history,stats,validRate]);
  const toggle=(id:string)=>setChecked(c=>{const n=new Set(c);n.has(id)?n.delete(id):n.add(id);return n;}); const toggleDate=(_:string,ids:string[])=>setChecked(c=>{const n=new Set(c);const all=ids.every(id=>n.has(id));ids.forEach(id=>all?n.delete(id):n.add(id));return n;});
  const cleanupIds=[...checked];
  const purge=async()=>{if(cleanupIds.length===0||purging)return;const selected=tasks.filter(t=>cleanupIds.includes(t.taskId));const confirmed=window.confirm(`确认清理 ${selected.length} 个任务的本地测量数据？\n任务目录中的 measurements.db 和单任务导出文件将被物理删除。\n任务索引仍保留，此操作不可撤销。`);if(!confirmed)return;setPurging(true);setPurgeMessage(null);setPurgeError(false);try{const r=await purgeTaskData(cleanupIds);setPurgeMessage(`已清理 ${r.removedTaskCount} 个任务，释放 ${bytes(r.releasedBytes)}`);setChecked(new Set());await onDataChanged();}catch(e){setPurgeError(true);setPurgeMessage(e instanceof Error?e.message:"任务数据清理失败");}finally{setPurging(false)}};
  const confirmDelete=async()=>{if(!selectedTask||deleteBlocked)return;setDeleting(true);setDeleteError(null);try{await onDeleteTask(selectedTask.taskId);setDeleteOpen(false);}catch(e){setDeleteError(e instanceof Error?e.message:"任务删除失败");}finally{setDeleting(false)}};
  const recordState=historyState==="loading"?"读取中":historyState==="ready"?`${stats?.validSamples??0} 条有效记录`:historyState==="error"?"读取失败":selectedTask?.localDataPurgedAt?"本地数据已清理":selectedTask?.hasMeasurements?"记录为空":selectedTask?"无记录":"--";
  return <div className="page-stack playback-page playback-page--clearance">
    <section className="panel workflow-context-bar"><div className="workflow-context-bar__identity"><span>当前任务</span><strong>{selectedTask?.displayId??"尚未选择任务"}</strong><small>{selectedTask?`${selectedTask.tunnelCode} · ${selectedTask.tunnelName} · ${selectedTask.status}`:"任务按创建日期分组，可多选或按整日清理本地数据"}</small></div><div className="workflow-context-bar__states"><div><span>任务状态</span><strong>{selectedTask?.status??"--"}</strong></div><div><span>高度记录</span><strong>{recordState}</strong></div><div><span>已选清理</span><strong>{checked.size} 项</strong></div><div><span>本地数据</span><strong>{selectedTask?.localDataPurgedAt?"已清理":selectedTask?.hasMeasurements?"存在":"无"}</strong></div></div><div className="workflow-context-bar__actions"><button type="button" className="button" onClick={()=>onNavigate("dashboard")}>返回采集首页</button><button type="button" className="button button--primary" disabled={!selectedTask} onClick={()=>onNavigate("report")}>进入报告导出</button><button type="button" className="button button--danger-outline" disabled={!selectedTask||deleteBlocked} onClick={()=>setDeleteOpen(true)}>删除任务</button><button type="button" className="button button--danger-outline" disabled={cleanupIds.length===0||purging} onClick={()=>void purge()}>{purging?"正在清理":`清理所选数据${cleanupIds.length?` (${cleanupIds.length})`:""}`}</button></div></section>
    {purgeMessage&&<p className={`batch-operation-message${purgeError?" is-error":""}`}>{purgeMessage}</p>}
    <section className="playback-layout playback-layout--clearance"><TaskBrowser tasks={tasks} selectedTaskId={selectedTaskId} onSelectTask={onSelectTask} heading="选择回放任务" selectable checkedTaskIds={checked} onToggleChecked={toggle} onToggleDateChecked={toggleDate}/><main className="playback-clearance-main"><article className="panel playback-clearance-panel"><header className="playback-clearance-panel__head"><div><span>50 Hz 测量序列</span><h2>{selectedTask?`${selectedTask.displayId} 完整净空高度曲线`:"完整净空高度曲线"}</h2><p>支持拖拽平移、滚轮缩放和双击复位，无效采样保持断开。</p></div><span className={`workflow-status ${history?.dataOrigin==="test_fixture"?"workflow-status--warn":taskEnded?"workflow-status--ok":"workflow-status--idle"}`}>{history?.dataOrigin==="test_fixture"?"界面测试数据":taskEnded?"任务已结束":selectedTask?"任务未结束":"待选择"}</span></header><InteractiveClearanceChart key={selectedTask?.taskId??"no-task"} samples={history?.samples??[]} emptyTitle={historyState==="loading"?"正在读取任务高度记录":historyState==="error"?"任务高度记录读取失败":selectedTask?.localDataPurgedAt?"本地测量数据已清理":selectedTask?"当前任务没有可显示的高度记录":"请选择任务查看完整净空高度曲线"} emptyDescription={historyState==="error"?historyError??"请检查后端日志。":selectedTask?.localDataPurgedAt?"任务索引仍保留，但 measurements.db 已按清理操作删除。":"页面不会使用模拟曲线替代缺失记录。"}/></article></main><aside className="panel playback-inspector playback-inspector--clearance"><header><div><span>任务记录</span><strong>统计与数据质量</strong></div></header><section className="inspector-section"><h3>隧道信息</h3><dl><div><dt>任务编号</dt><dd>{selectedTask?.displayId??"--"}</dd></div><div><dt>隧道编号</dt><dd>{selectedTask?.tunnelCode??"--"}</dd></div><div><dt>隧道名称</dt><dd>{selectedTask?.tunnelName??"--"}</dd></div><div><dt>检测车道</dt><dd>{history?.lane??selectedTask?.lane??"未记录"}</dd></div></dl></section><section className="inspector-section"><h3>测量统计</h3><dl>{measurementRows.map(([l,v])=><div key={l}><dt>{l}</dt><dd>{v}</dd></div>)}</dl></section><section className="inspector-section"><h3>隧道端点</h3><dl><div><dt>入口 RTK</dt><dd>{frtk(history?.entryRtk??null)}</dd></div><div><dt>出口 RTK</dt><dd>{frtk(history?.exitRtk??null)}</dd></div></dl></section><section className="inspector-section"><h3>数据质量</h3><dl>{qualityRows.map(([l,v])=><div key={l}><dt>{l}</dt><dd>{v}</dd></div>)}</dl></section></aside></section>
    {deleteOpen&&selectedTask&&<DeleteDialog task={selectedTask} deleting={deleting} error={deleteError} onCancel={()=>!deleting&&setDeleteOpen(false)} onConfirm={()=>void confirmDelete()}/>}
  </div>;
}
