"use client";

import { useEffect, useMemo, useState } from "react";
import { cancelExportJob, downloadExportJob, loadExportJob, loadReportPreview, startDeepSeekReportJob, startSummaryPdfJob, startTaskTxtJob, type DeepSeekModel, type ExportJob, type ReportPreview, type ReportRtkEndpoint, type ReportTaskPreview } from "@/components/report/reportExportApi";
import TaskBrowser from "@/components/workflow/TaskBrowser";
import type { CollectionTask, WorkflowPageId } from "@/components/workflow/taskModel";

type Props={tasks:CollectionTask[];selectedTaskId:string|null;onSelectTask:(id:string)=>void;onNavigate:(page:WorkflowPageId)=>void};
type PreviewState="idle"|"loading"|"ready"|"error"; type ExportState="idle"|"generating"|"done"|"error";
type ExportKind="txt"|"pdf"|"deepseek";
const pdfColumns=["任务编号","隧道编号","检测车道","原始单帧最低 m","建议最低可信净空 m","可信度","记录时间","隧道入口 RTK","隧道出口 RTK"];
const statusText:Record<ReportTaskPreview["status"],string>={pending:"待执行",running:"采集中",paused:"已暂停",completed:"已停止",interrupted:"异常中断",failed:"失败"};
const fh=(v:number|null)=>v===null?"--":`${v.toFixed(3)} m`; const fc=(v:number|null,l:string|null)=>{if(v===null)return"--";const label=l?({HIGH:"高",MEDIUM:"中",LOW:"低",INSUFFICIENT:"证据不足"}[l]??l):"";return`${v}/100${label?` · ${label}`:""}`}; const ft=(v:string|null)=>{if(!v)return"--";const d=new Date(v);return Number.isNaN(d.getTime())?"--":d.toLocaleString("zh-CN",{hour12:false})};
const fr=(e:ReportRtkEndpoint|null)=>!e||!e.valid?"未记录":`${e.latitudeDeg.toFixed(7)}, ${e.longitudeDeg.toFixed(7)}`; const et=(e:unknown)=>e instanceof Error?e.message:"导出操作失败";
const DEEPSEEK_API_KEY_STORAGE="capture-deepseek-api-key"; const DEEPSEEK_MODEL_STORAGE="capture-deepseek-model";
const jobKey=(kind:ExportKind)=>`capture-export-job-${kind}`; const wait=(ms:number)=>new Promise(resolve=>window.setTimeout(resolve,ms));

export default function ReportWorkspace({tasks,selectedTaskId,onSelectTask,onNavigate}:Props){
  const [checked,setChecked]=useState<Set<string>>(()=>new Set(selectedTaskId?[selectedTaskId]:[]));
  const [previewState,setPreviewState]=useState<PreviewState>("idle"); const [preview,setPreview]=useState<ReportPreview|null>(null); const [previewError,setPreviewError]=useState<string|null>(null);
  const [txtState,setTxtState]=useState<ExportState>("idle"); const [pdfState,setPdfState]=useState<ExportState>("idle"); const [deepseekState,setDeepSeekState]=useState<ExportState>("idle"); const [txtMessage,setTxtMessage]=useState<string|null>(null); const [pdfMessage,setPdfMessage]=useState<string|null>(null); const [deepseekMessage,setDeepSeekMessage]=useState<string|null>(null);
  const [txtJob,setTxtJob]=useState<ExportJob|null>(null); const [pdfJob,setPdfJob]=useState<ExportJob|null>(null); const [deepseekJob,setDeepSeekJob]=useState<ExportJob|null>(null);
  const [deepseekApiKey,setDeepSeekApiKey]=useState(""); const [deepseekModel,setDeepSeekModel]=useState<DeepSeekModel>("deepseek-v4-flash");
  const selectedTask=tasks.find(t=>t.taskId===selectedTaskId)??null; const selectedIds=useMemo(()=>tasks.filter(t=>checked.has(t.taskId)).map(t=>t.taskId),[checked,tasks]);
  const previewIds=useMemo(()=>selectedTaskId&& !selectedIds.includes(selectedTaskId)?[...selectedIds,selectedTaskId]:selectedIds,[selectedIds,selectedTaskId]);
  const revision=useMemo(()=>tasks.map(t=>`${t.taskId}:${t.updatedAt}:${t.hasMeasurements}`).join("|"),[tasks]);
  useEffect(()=>{setChecked(current=>{const next=new Set([...current].filter(id=>tasks.some(t=>t.taskId===id)));if(next.size===0&&selectedTaskId&&tasks.some(t=>t.taskId===selectedTaskId))next.add(selectedTaskId);return next;});},[revision,tasks,selectedTaskId]);
  useEffect(()=>{const savedKey=localStorage.getItem(DEEPSEEK_API_KEY_STORAGE);const savedModel=localStorage.getItem(DEEPSEEK_MODEL_STORAGE);if(savedKey)setDeepSeekApiKey(savedKey);if(savedModel==="deepseek-v4-flash"||savedModel==="deepseek-v4-pro")setDeepSeekModel(savedModel);},[]);
  useEffect(()=>{const controller=new AbortController();if(previewIds.length===0){setPreview(null);setPreviewState("idle");return()=>controller.abort();}setPreviewState("loading");setPreviewError(null);loadReportPreview(previewIds,controller.signal).then(p=>{setPreview(p);setPreviewState("ready")}).catch(e=>{if(!controller.signal.aborted){setPreview(null);setPreviewState("error");setPreviewError(et(e))}});return()=>controller.abort();},[previewIds.join("|"),revision]);
  const selectedPreview=preview?.tasks.find(t=>t.taskId===selectedTaskId)??null; const pdfExportableTasks=preview?.tasks.filter(t=>checked.has(t.taskId)&&t.pdfExportable)??[]; const txtReady=selectedPreview?.exportable===true; const pdfReady=pdfExportableTasks.length>0; const deepseekReady=selectedPreview?.pdfExportable===true&&deepseekApiKey.trim().length>0;
  const toggle=(id:string)=>setChecked(c=>{const n=new Set(c);n.has(id)?n.delete(id):n.add(id);return n;});
  const toggleDate=(_:string,ids:string[])=>setChecked(c=>{const n=new Set(c);const all=ids.every(id=>n.has(id));ids.forEach(id=>all?n.delete(id):n.add(id));return n;});
  const followJob=async(kind:ExportKind,initial:ExportJob,signal?:AbortSignal)=>{const ss=kind==="txt"?setTxtState:kind==="pdf"?setPdfState:setDeepSeekState;const sm=kind==="txt"?setTxtMessage:kind==="pdf"?setPdfMessage:setDeepSeekMessage;const sj=kind==="txt"?setTxtJob:kind==="pdf"?setPdfJob:setDeepSeekJob;let current=initial;sj(current);ss("generating");while(current.state==="queued"||current.state==="running"){if(signal?.aborted)return;sm(`${current.phase} ${Math.round(current.progress*100)}%`);await wait(750);current=await loadExportJob(current.jobId,signal);sj(current);}localStorage.removeItem(jobKey(kind));if(current.state==="completed"){downloadExportJob(current);ss("done");sm(`${current.fileName??"导出文件"} 已生成并开始下载`);}else if(current.state==="cancelled"){ss("idle");sm("导出任务已取消");}else{ss("error");sm(current.error??"导出任务失败");}};
  const run=async(kind:ExportKind,starter:()=>Promise<ExportJob>)=>{const ss=kind==="txt"?setTxtState:kind==="pdf"?setPdfState:setDeepSeekState;const sm=kind==="txt"?setTxtMessage:kind==="pdf"?setPdfMessage:setDeepSeekMessage;ss("generating");sm("正在提交导出任务");try{const created=await starter();localStorage.setItem(jobKey(kind),created.jobId);await followJob(kind,created);}catch(e){ss("error");sm(et(e));}};
  const cancel=async(kind:ExportKind,current:ExportJob|null)=>{if(!current)return;const sm=kind==="txt"?setTxtMessage:kind==="pdf"?setPdfMessage:setDeepSeekMessage;try{await cancelExportJob(current.jobId);localStorage.removeItem(jobKey(kind));(kind==="txt"?setTxtState:kind==="pdf"?setPdfState:setDeepSeekState)("idle");sm("导出任务已取消");}catch(e){sm(et(e));}};
  useEffect(()=>{const controller=new AbortController();(["txt","pdf","deepseek"] as const).forEach(kind=>{const id=localStorage.getItem(jobKey(kind));if(id)loadExportJob(id,controller.signal).then(job=>followJob(kind,job,controller.signal)).catch(e=>{if(!controller.signal.aborted)(kind==="txt"?setTxtMessage:kind==="pdf"?setPdfMessage:setDeepSeekMessage)(et(e));});});return()=>controller.abort();},[]);
  const saveDeepSeekApiKey=(value:string)=>{setDeepSeekApiKey(value);localStorage.setItem(DEEPSEEK_API_KEY_STORAGE,value);};
  const saveDeepSeekModel=(value:DeepSeekModel)=>{setDeepSeekModel(value);localStorage.setItem(DEEPSEEK_MODEL_STORAGE,value);};
  const blocker=!selectedTask?"请先选择需要导出明细的任务":selectedPreview?.blockedReason??(txtReady?"当前任务满足正式 TXT 导出条件":"请将当前任务加入 PDF 选择后核对导出条件");
  return <div className="page-stack report-page report-page--simple">
    <section className="panel workflow-context-bar"><div className="workflow-context-bar__identity"><span>报告选择</span><strong>{checked.size} 个任务已选择</strong><small>TXT 和大模型报告面向当前任务，PDF 汇总完成异常分析且包含有效净空的勾选任务</small></div><div className="workflow-context-bar__states"><div><span>当前任务</span><strong>{selectedTask?.displayId??"--"}</strong></div><div><span>已选择</span><strong>{checked.size} 项</strong></div><div><span>可汇总</span><strong className={pdfReady?"is-ready":"is-pending"}>{previewState==="ready"?`${pdfExportableTasks.length}/${selectedIds.length}`:"--"}</strong></div><div><span>导出接口</span><strong className={previewState==="error"?"is-blocked":"is-ready"}>{previewState==="error"?"异常":"可用"}</strong></div></div><div className="workflow-context-bar__actions"><button type="button" className="button" onClick={()=>onNavigate("playback")}>返回数据回放</button><button type="button" className="button button--primary" onClick={()=>onNavigate("dashboard")}>返回采集首页</button></div></section>
    {previewError&&<p className="batch-operation-message is-error" role="alert">{previewError}</p>}
    <section className="report-simple-layout">
      <TaskBrowser tasks={tasks} selectedTaskId={selectedTaskId} onSelectTask={onSelectTask} heading="选择导出任务" sortOrder="asc" selectable checkedTaskIds={checked} onToggleChecked={toggle} onToggleDateChecked={toggleDate}/>
      <main className="report-simple-main">
        <article className="panel report-task-summary"><header className="report-simple-heading"><div><span>当前任务</span><h2>{selectedTask?.displayId??"导出对象"}</h2></div><strong className={txtReady?"is-ready":"is-pending"}>{selectedPreview?statusText[selectedPreview.status]:selectedTask?.status??"待选择"}</strong></header><dl className="report-task-summary__grid"><div><dt>任务编号</dt><dd>{selectedTask?.displayId??"--"}</dd></div><div><dt>创建时间</dt><dd>{ft(selectedTask?.createdAt??null)}</dd></div><div><dt>隧道编号</dt><dd>{selectedTask?.tunnelCode??"--"}</dd></div><div><dt>隧道名称</dt><dd>{selectedTask?.tunnelName??"--"}</dd></div><div><dt>检测车道</dt><dd>{selectedPreview?.lane??selectedTask?.lane??"未记录"}</dd></div></dl><p className={`report-export-blocker${txtReady?" is-ready":""}`}><strong>{txtReady?"可以导出":"当前不能导出"}</strong><span>{blocker}</span></p></article>
        <section className="report-export-grid">
          <article className="panel report-export-card report-export-card--txt"><header className="report-export-card__head"><span className="report-export-card__type">TXT</span><div><h2>50 Hz 测量明细</h2><p>输出RTK时间、净空、最近源帧来源、IMU平均值、最低点和ODIN姿态位置。</p></div><strong>50 Hz</strong></header><footer className="report-export-card__footer"><div><span>文件名称</span><strong>{selectedTask?`${selectedTask.displayId}_${selectedTask.tunnelCode}_50Hz测量明细.txt`:"时间编号_隧道编号_50Hz测量明细.txt"}</strong>{txtMessage&&<small className={txtState==="error"?"is-error":"is-success"}>{txtMessage}</small>}</div><button type="button" className="button button--primary" disabled={!txtReady} onClick={()=>txtState==="generating"?cancel("txt",txtJob):selectedTask&&run("txt",()=>startTaskTxtJob(selectedTask.taskId))}>{txtState==="generating"?"取消导出":"导出 TXT"}</button></footer></article>
          <article className="panel report-export-card report-export-card--pdf">
            <header className="report-export-card__head"><span className="report-export-card__type">PDF</span><div><h2>隧道净空检测汇总</h2><p>保留现有汇总报告，并可为当前任务生成一份大模型辅助分析报告。</p></div><strong>{pdfExportableTasks.length} 项</strong></header>
            <section className="report-pdf-outline"><header><span>报告标题</span><strong>隧道净空检测汇总报告</strong></header><div className="report-pdf-table"><div className="report-pdf-table__row report-pdf-table__row--head">{pdfColumns.map(c=><span key={c}>{c}</span>)}</div>{pdfExportableTasks.length===0?<div className="report-pdf-table__row">{pdfColumns.map(c=><span key={c}>--</span>)}</div>:pdfExportableTasks.map(t=><div className="report-pdf-table__row" key={t.taskId}><span>{t.displayId}</span><span>{t.tunnelCode}</span><span>{t.lane??"未记录"}</span><span>{fh(t.rawMinClearanceM)}</span><span>{fh(t.recommendedMinClearanceM)}</span><span title={t.confidenceReason??undefined}>{fc(t.confidenceScore,t.confidenceLevel)}</span><span>{ft(t.startedAt)}</span><span>{fr(t.entryRtk)}</span><span>{fr(t.exitRtk)}</span></div>)}</div><p>可信度是单个任务内部的0–100证据评分，不是统计概率。建议值至少需要5个几何合格独立源帧，证据不足时显示“--”，不会复制原始最低值。真实连续结构和周期性设施受到保护，原始记录不会被修改。</p></section>
            <section className="deepseek-report-config"><header><div><strong>DeepSeek大模型辅助分析</strong><span>API Key保存在当前显示端；每次点击都创建一个新的模型任务窗口。</span></div><span>当前任务：{selectedTask?.displayId??"--"}</span></header><div className="deepseek-report-config__fields"><label><span>DeepSeek API Key</span><input type="password" autoComplete="off" value={deepseekApiKey} placeholder="请输入DeepSeek API Key" onChange={event=>saveDeepSeekApiKey(event.target.value)}/></label><label><span>分析模型</span><select value={deepseekModel} onChange={event=>saveDeepSeekModel(event.target.value as DeepSeekModel)}><option value="deepseek-v4-flash">deepseek-v4-flash</option><option value="deepseek-v4-pro">deepseek-v4-pro</option></select></label></div><small>第一版读取当前任务完整measurements.db并使用单次请求，不进行长任务分块。数据超过单窗口上限时会明确失败，不截断报告数据。</small>{deepseekMessage&&<p className={deepseekState==="error"?"is-error":"is-success"}>{deepseekMessage}</p>}</section>
            <footer className="report-export-card__footer"><div><span>文件名称</span><strong>现有汇总报告.pdf　/　当前任务_大模型辅助分析报告.pdf</strong>{pdfMessage&&<small className={pdfState==="error"?"is-error":"is-success"}>{pdfMessage}</small>}</div><div className="report-export-card__actions"><button type="button" className="button" disabled={!pdfReady} onClick={()=>pdfState==="generating"?cancel("pdf",pdfJob):run("pdf",()=>startSummaryPdfJob(selectedIds))}>{pdfState==="generating"?"取消导出":"导出 PDF"}</button><button type="button" className="button button--primary" disabled={!deepseekReady} onClick={()=>deepseekState==="generating"?cancel("deepseek",deepseekJob):selectedTask&&run("deepseek",()=>startDeepSeekReportJob(selectedTask.taskId,deepseekApiKey,deepseekModel))}>{deepseekState==="generating"?"取消大模型导出":"大模型报告导出"}</button></div></footer>
          </article>
        </section>
      </main>
    </section>
  </div>;
}
